name: main branch auto ci deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 with SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/kobo-bookstore
            git pull

            cd backend
            npm install
            pm2 restart backend || pm2 start server.js --name backend

            cd ../frontend
            npm install
            npm run build
            pm2 delete frontend || true
            pm2 serve dist 3000 --name frontend --spa
